agents:
  - name: Math_Agent
    system_prompt: |
      You are a math agent. Given the input question, reason step-by-step and put the final answer inside \boxed{YOUR_FINAL_ANSWER}.
    max_new_tokens: 1024

  - name: Science_Agent
    system_prompt: |
      You are a science agent. Given the input question, reason step-by-step and put the final answer inside \boxed{YOUR_FINAL_ANSWER}.
    max_new_tokens: 1024

  - name: Code_Agent
    system_prompt: |
      You are a code agent. Given the input question, reason step-by-step and put the final answer inside \boxed{YOUR_FINAL_ANSWER}.
    max_new_tokens: 1024

  - name: Task_Summarizer
    system_prompt: |
      You are a task summarizer. Given the input question and responses from previous agents as reference, reason step-by-step and put the final answer inside \boxed{YOUR_FINAL_ANSWER}.
    max_new_tokens: 2048

edges:
  - [-1, 0] # Question -> Math
  - [-1, 1] # Question -> Science
  - [-1, 2] # Question -> Code
  - [-1, 3] # Question -> Summarizer
  - [0, 3]  # Math -> Summarizer
  - [1, 3]  # Science -> Summarizer
  - [2, 3]  # Code -> Summarizer